var {XFetch,PFetch,upload,host,token} = require('../network/fetch');
var async = require('async')
var Push = require('../network/push');
var AppDispatcher = require('../dispatcher/appDispatcher');
var Command = require('../../constants/command');
var ActionTypes = Command.ActionTypes;
var _ = require('lodash');
var pub = "/pub";
var api = "/api"
var Actions = {}
module.exports = Actions;